config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  get 'general/welcome'

  resources :patients
  resources :appointments

  devise_for :users, :controllers => {registrations: 'registrations'}
  devise_scope :user do
   get "/registrations/index" => 'registrations#index'
  end
  resources :users

  root 'appointments#index'
  get 'destroy_appointment' => 'appointments#destroy'
  get 'paid' => 'invoices#paid'
  get 'unpaid' => 'invoices#unpaid'
  get 'paid_list' => 'invoices#paid_list'
  get 'unpaid_list' => 'invoices#unpaid_list'
  get 'sort_invoices' => 'invoices#sort_invoices'
  post 'sort_invoices' => 'invoices#sort_invoices'
  get 'sort_appointments' => 'appointments#sort_appointments'
  post 'sort_appointments' => 'appointments#sort_appointments'
  get 'sort_appointments_list' => 'appointments#sort_appointments_list'
  post 'sort_appointments_list' => 'appointments#sort_appointments_list'
  get 'auto_create' => 'invoices#auto_create'
  get 'destroy_invoice' => 'invoices#destroy'
  # AJAX pages
  get 'all_appointments' => 'appointments#all_appointments'

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  def to_hours
    self / (60*60)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy, :paid, :unpaid, :paid_list, :unpaid_list]
  before_action :set_invoices, only: [:index, :sort_invoices]
  before_action :set_interpreters, only: [:index, :paid, :unpaid, :paid_list, :unpaid_list, :sort_invoices, :destroy]
  respond_to :html, :js

  # GET /invoices
  # GET /invoices.json
  def index
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @appointments = Appointment.where('invoice_id = ?', @invoice.id)
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  def auto_create
    @appointments = Appointment.where('complete = ? OR no_show = ? AND invoice_id IS NULL', true, true).where.not(user_id: nil)
    @users = @appointments.map {|x| User.find(x.user_id)}
    @users = @users.uniq
    @invoices = []
    @users.each do |user|
      appointments = Appointment.where('user_id = ?', user.id).where('complete = ? AND invoice_id IS NULL OR no_show = ? AND invoice_id IS NULL' ,true, true)
      invoice = Invoice.new(user_id: user.id, start_date: appointments.order('start_time asc').limit(1)[0].start_time.strftime("%y-%m-%d"), end_date: appointments.order('start_time desc').limit(1)[0].start_time.strftime("%y-%m-%d"))
      invoice.miles_total = appointments.reduce(0){|sum, x| sum + x.miles_driven}
      invoice.hours_total = appointments.reduce(0){|sum, x| sum + (x.end_time - x.start_time) / (60*60)}
      invoice.total_paid = ((invoice.hours_total * user.hourly_rate) + (invoice.miles_total * user.mileage_rate))
      invoice.save!
      @invoices << invoice
      appointments.map {|appt| appt.invoice_id = invoice.id; appt.save!}
    end
    @invoices
  end
  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    user = User.find(@invoice.user_id)
    appointments = appointments = Appointment.where('user_id = ?', user.id).where('start_time >= ? AND end_time <= ? AND complete = ? OR start_time >= ? AND end_time <= ? AND no_show = ?', @invoice.start_date, @invoice.end_date, true, @invoice.start_date, @invoice.end_date, true)
    unless appointments.empty?
      @invoice.miles_total = appointments.reduce(0){|sum, x| sum + x.miles_driven}
      @invoice.hours_total = appointments.reduce(0){|sum, x| sum + (x.end_time - x.start_time) / (60*60)}
      @invoice.total_paid = ((@invoice.hours_total * user.hourly_rate) + (@invoice.miles_total * user.mileage_rate))
      @invoice.save!
      appointments.map {|appt| appt.invoice_id = @invoice.id; appt.save!}
      render notice: "Invoice was succesfully created."
    else
      render :new, notice: 'Invoice was unable to be created. No appointments in this time frame.'
    end

  end
  # GET
  def paid
    mark_paid(@invoice)
    set_invoices
    render notice: "Invoice and coorsponding appointments were successfully marked as paid."
  end
  # GET
  def unpaid
    mark_unpaid(@invoice)
    set_invoices
    render notice: "Invoice and coorsponding appointments were successfully marked as unpaid."
  end

  # GET
  def paid_list
    mark_paid(@invoice)
    set_invoices
    render notice: "Invoice and coorsponding appointments were successfully marked as paid."
  end
  # GET
  def unpaid_list
    mark_unpaid(@invoice)
    set_invoices
    render notice: "Invoice and coorsponding appointments were successfully marked as unpaid."
  end
  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    @invoice.update(invoice_params)

    @appointments = Appointment.all
    redirect_to @invoice
  end

  def sort_invoices
    if params[:user][:id] == ""
      @sorted_invoices = Invoice.all
    else
      @user = User.find(params[:user][:id])
      @sorted_invoices = Invoice.where('user_id = ?', @user.id)
    end
    @sorted_invoices
  end
  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    appointments = Appointment.where('invoice_id = ?', @invoice.id)
    appointments.map {|appt| appt.invoice_id = nil; appt.save!}
    @invoice.destroy
    @invoices = Invoice.all.order("start_date ASC")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def mark_unpaid(invoice)
      @appointments = Appointment.all.where('invoice_id = ?', invoice.id)
      @appointments.map {|appt| appt.paid_for = false; appt.save}
      invoice.paid_on = nil
      invoice.save
    end

    def mark_paid(invoice)
      @appointments = Appointment.where('invoice_id = ?', invoice.id)
      @appointments.map {|appt| appt.paid_for = true; appt.save}
      invoice.paid_on = Date.today
      invoice.save
    end

    def set_interpreters
      @invoices = Invoice.all
      @interpreters = @invoices.map {|x| User.find(x.user_id)}
      @interpreters = @interpreters.uniq
    end

    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def set_invoices
      @invoices = Invoice.all.order("start_date ASC")
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:user_id, :miles_total, :hours_total, :total_paid, :paid_on, :start_date, :end_date)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_all_appointments.html.erb
<p id="notice"><%= notice %></p>

<% unless @appointments.empty? %>
  <table id="table" class="table table-hover" data-smart-display="true" data-toggle="table" align="center">
    <thead>
      <tr>
        <th>Patient</th>
        <th>Interpreter</th>
        <th>Note</th>
        <th>Clinic</th>
        <th>Complete</th>
        <th>No Show</th>
        <th>Paid for</th>
        <th>Cancelled</th>
        <th>Date</th>
        <th>Start time</th>
        <th>End time</th>
        <th>Hours</th>
        <th>Miles</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @appointments.each do |appointment| %>
        <tr>
          <td><%= appointment.patient.full_name %></td>
          <td><%= appointment.user.full_name %></td>
          <td><%= appointment.note %></td>
          <td><%= appointment.clinic %></td>
          <td><%= appointment.complete %></td>
          <td><%= appointment.no_show %></td>
          <td><%= appointment.paid_for %></td>
          <td><%= appointment.cancelled %></td>
          <td><%= appointment.start_time.strftime("%D") if appointment.start_time %></td>
          <td><%= appointment.start_time.strftime("%l:%M%p") if appointment.start_time %></td>
          <td><%= appointment.end_time.strftime("%l:%M%p") if appointment.end_time %></td>
          <td><%= (appointment.end_time - appointment.start_time) / (60*60) %></td>
          <td><%= appointment.miles_driven.round(2) %></td>
          <td><%= link_to 'Show', appointment, remote: true %></td>
          <td><%= link_to 'Edit', edit_appointment_path(appointment), remote: true %></td>
          <td><%= link_to 'Delete', appointment, method: :delete, data: { confirm: 'This action will delete the original as well as remove it from this invoice. Are you sure you want to proceed?' }, remote: true %></td>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>Totals:</strong></td>
        <td><strong><%= @invoice.hours_total.round(2) %></strong></td>
        <td><strong><%= @invoice.miles_total %></strong></td>
        <td colspan="3"><strong><%= number_to_currency(@invoice.total_paid) %></strong></td>
      </tr>
    </tbody>
  </table>
<% else %>
  <h2>There are no appointments to display. Create some appointments! </h2>
<% end %>
<br>

app/views/invoices/_auto_create.html.erb
<p id="notice"><%= notice %></p>

<% unless @invoices.empty? %>
  <h1>Invoices</h1>

  <table id="table" class="table table-hover col-sm-12" data-smart-display="true" data-toggle="table" align="center">
    <thead>
      <tr>
        <th>Interpreter</th>
        <th>Miles total</th>
        <th>Hours total</th>
        <th>Total paid</th>
        <th>Total owed</th>
        <th>Paid on</th>
        <th>Start date</th>
        <th>End date</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.user.full_name %></td>
          <td><%= invoice.miles_total.round(2) %></td>
          <td><%= invoice.hours_total.round(2) %></td>
          <td><%= number_to_currency(invoice.total_paid) if invoice.paid_on %></td>
          <td><%= number_to_currency(invoice.total_paid) unless invoice.paid_on %></td>
          <td><%= invoice.paid_on.strftime("%D") if invoice.paid_on %></td>
          <td><%= invoice.start_date.strftime("%D") %></td>
          <td><%= invoice.end_date.strftime("%D") %></td>
          <td><%= link_to 'Show', invoice, remote: true %></td>
          <td><%= link_to 'Detailed', invoice %></td>
          <td><%= link_to 'Edit', edit_invoice_path(invoice), remote: true %></td>
          <% if invoice.paid_on.present? %>
            <td><%= link_to 'Unpay', unpaid_list_path(id: invoice), data: { confirm: "Are you sure this invoice wasn't paid?" }, remote: true %></td>
          <% else %>
            <td><%= link_to 'Pay', paid_list_path(id: invoice), data: { confirm: 'Are you sure this invoice was paid?' }, remote: true %></td>
          <% end %>
          <td><%= link_to 'Destroy', destroy_invoice_path(id: invoice), data: { confirm: 'Are you sure?' }, remote: true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>All completed appointments have already been invoiced. Create new completed appointments to create new invoices!</h2>
<% end %>

app/views/invoices/_form.html.erb
<%= form_for(@invoice, remote: true) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Interpreter" %>
    <%= f.collection_select(:user_id, User.all, :id, :full_name) %>
  </div>

  <div class="field">
    <%= f.label :miles_total %>
    <%= f.text_field :miles_total %>
  </div>

  <div class="field">
    <%= f.label :hours_total %>
    <%= f.text_field :hours_total %>
  </div>

  <div class="field">
    <%= f.label :total_paid %>
    <%= f.text_field :total_paid %>
  </div>

  <div class="field">
    <%= f.label :paid_on %>
    <%= f.date_select :paid_on, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success", remote: true %>
  </div>
<% end %>

app/views/invoices/_show.html.erb
<div class="text-center">
  <%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn btn-primary" %> |
  <%= link_to 'Back', appointments_path, class: "btn btn-warning" %> |
  <% if @invoice.paid_on.present? %>
    <td><%= link_to 'Unpay', unpaid_path(id: @invoice), class: "btn btn-success", data: { confirm: "Are you sure this invoice wasn't paid?" }, remote: true %></td>
  <% else %>
    <td><%= link_to 'Pay', paid_path(id: @invoice), class: "btn btn-success", data: { confirm: 'Are you sure this invoice was paid?' }, remote: true %></td>
  <% end %>
</div>
<div class="text-center hidden-md-up">
  <h3>Summary</h3>
  <p>
    <strong>Number of appointments:</strong>
    <%= @appointments.count %>
  </p>
  <p>
    <strong>Miles total:</strong>
    <%= @invoice.miles_total.round(2) %>
  </p>

  <p>
    <strong>Hours total:</strong>
    <%= @invoice.hours_total.round(2) %>
  </p>

  <p>
    <strong>Paid date:</strong>
    <% if @invoice.paid_on %>
      <%= @invoice.paid_on.strftime("%D") if @invoice.paid_on %>
    <% else %>
      Not paid yet
    <% end %>
  </p>

  <h3>
    <strong><%= "Total owed:" unless @invoice.paid_on %><%= "Total paid:" if @invoice.paid_on %></strong>
    <%= number_to_currency(@invoice.total_paid) %>
  </h3>
</div>
<div class="hidden-md-down">
  <h3>Summary</h3>
  <p>
    <strong>Number of appointments:</strong>
    <%= @appointments.count %>
  </p>
  <p>
    <strong>Miles total:</strong>
    <%= @invoice.miles_total.round(2) %>
  </p>

  <p>
    <strong>Hours total:</strong>
    <%= @invoice.hours_total.round(2) %>
  </p>

  <p>
    <strong>Paid date:</strong>
    <% if @invoice.paid_on %>
      <%= @invoice.paid_on.strftime("%D") if @invoice.paid_on %>
    <% else %>
      Not paid yet
    <% end %>
  </p>

  <h3>
    <strong><%= "Total owed:" unless @invoice.paid_on %><%= "Total paid:" if @invoice.paid_on %></strong>
    <%= number_to_currency(@invoice.total_paid) %>
  </h3>
</div>

app/views/invoices/auto_create.js.erb
$(".ajax").html("<%= j(render 'auto_create', locals: { :invoices => @invoices}) %>");

app/views/invoices/create.js.erb
$(".ajax").html("<%= j(render 'show') %>");

app/views/invoices/edit.html.erb
<div class="text-center">
  <h1>Editing Invoice</h1>
  <%= render 'form', invoice: @invoice %>

  <%= link_to 'Back', @invoice, class: "btn btn-warning" %> |
  <%= link_to 'Delete', @invoice,  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>

app/views/invoices/edit.js.erb
$(".ajax").html("<%= j(render 'edit') %>");

app/views/invoices/new.js.erb
$(".ajax").html("<%= j(render 'new') %>");

app/views/invoices/paid_list.js.erb
$(".ajax").html("<%= j(render 'index') %>");

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
  <h1>Invoice for <%= @invoice.user.first_name %></h1>
  <h4><%= @invoice.start_date.strftime("%D") if @invoice.start_date %> to <%= @invoice.end_date.strftime("%D") if @invoice.end_date %></h4>
  <div class="ajax">
    <%= render partial: 'all_appointments', locals: {invoice: @invoice} %>
  </div>
</div>
  <div class="invoice">
    <%= render 'show' %>
  </div>

app/views/invoices/sort_invoices.js.erb
$(".ajax").html("<%= j(render 'sort_invoices', locals: { :sorted_invoices => @sorted_invoices}) %>");

app/views/invoices/unpaid.js.erb
$(".ajax").html("<%= j(render 'all_appointments') %>");
$(".invoice").html("<%= j(render 'show') %>");

app/views/invoices/unpaid_list.js.erb
$(".ajax").html("<%= j(render 'index') %>");