config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  get 'general/welcome'

  resources :patients
  resources :appointments

  devise_for :users, :controllers => {registrations: 'registrations'}
  devise_scope :user do
   get "/registrations/index" => 'registrations#index'
  end
  resources :users

  root 'appointments#index'
  get 'destroy_appointment' => 'appointments#destroy'
  get 'paid' => 'invoices#paid'
  get 'unpaid' => 'invoices#unpaid'
  get 'paid_list' => 'invoices#paid_list'
  get 'unpaid_list' => 'invoices#unpaid_list'
  get 'sort_invoices' => 'invoices#sort_invoices'
  post 'sort_invoices' => 'invoices#sort_invoices'
  get 'sort_appointments' => 'appointments#sort_appointments'
  post 'sort_appointments' => 'appointments#sort_appointments'
  get 'sort_appointments_list' => 'appointments#sort_appointments_list'
  post 'sort_appointments_list' => 'appointments#sort_appointments_list'
  get 'auto_create' => 'invoices#auto_create'
  get 'destroy_invoice' => 'invoices#destroy'
  # AJAX pages
  get 'all_appointments' => 'appointments#all_appointments'

end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :users
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_format_of :email, with: /@/
  validates :phone_number, presence: true
  
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    unless @patient.save
      render :new, notice: 'Appointment was unable to be created. Check your fields.'
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    @patient.update(patient_params)

    @appointemnts = Appointment.all
    redirect_to @patient
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    render :close_all
  end

  def close_all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :email, :phone_number)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient, remote: true %>

<%= link_to 'Show', @patient, class: "btn btn-primary", remote: true %> |
<%= link_to 'Back', appointments_path, class: "btn btn-warning" %> |
<%= link_to 'Delete', @patient,  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", remote: true %>

app/views/patients/_form.html.erb
<%= form_for(@patient, remote: true) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div><br />

  <div class="actions">
    <%= f.submit class: "btn btn-success", remote: true %>
  </div>
<% end %>

app/views/patients/_index.html.erb
<p id="notice"><%= notice %></p>

<% unless @patients.empty? %>
  <h1>Patients List</h1>
  <table id="table" class="table table-hover" data-smart-display="true" data-toggle="table" align="center">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Phone number</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody align="center">
      <% @patients.each do |patient| %>
        <tr>
          <td><%= patient.first_name %></td>
          <td><%= patient.last_name %></td>
          <td><%= patient.email %></td>
          <td><%= patient.phone_number %></td>
          <td><%= link_to 'Show', patient, remote: true %></td>
          <td><%= link_to 'Edit', edit_patient_path(patient), remote: true %></td>
          <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>There are no patients to display. Create some patients!</h2>
<% end %>

<br>

app/views/patients/_new.html.erb
<h1>Create Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path, remote: true %>

app/views/patients/_show.html.erb
<p id="notice"><%= notice %></p>
<h1>Patient</h1>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @patient.phone_number %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient), class: "btn btn-primary", remote: true %> |
<%= link_to 'Back', appointments_path, class: "btn btn-warning" %>

app/views/patients/close_all.js.erb
$(".ajax").html("");

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.email %></td>
        <td><%= patient.phone_number %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.js.erb
$(".ajax").html("<%= j(render 'new') %>");

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @patient.phone_number %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>