config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  get 'general/welcome'

  resources :patients
  resources :appointments

  devise_for :users, :controllers => {registrations: 'registrations'}
  devise_scope :user do
   get "/registrations/index" => 'registrations#index'
  end
  resources :users

  root 'appointments#index'
  get 'destroy_appointment' => 'appointments#destroy'
  get 'paid' => 'invoices#paid'
  get 'unpaid' => 'invoices#unpaid'
  get 'paid_list' => 'invoices#paid_list'
  get 'unpaid_list' => 'invoices#unpaid_list'
  get 'sort_invoices' => 'invoices#sort_invoices'
  post 'sort_invoices' => 'invoices#sort_invoices'
  get 'sort_appointments' => 'appointments#sort_appointments'
  post 'sort_appointments' => 'appointments#sort_appointments'
  get 'sort_appointments_list' => 'appointments#sort_appointments_list'
  post 'sort_appointments_list' => 'appointments#sort_appointments_list'
  get 'auto_create' => 'invoices#auto_create'
  get 'destroy_invoice' => 'invoices#destroy'
  # AJAX pages
  get 'all_appointments' => 'appointments#all_appointments'

end

app/views/layouts/_user_header.html.erb
<nav class="navbar navbar-fixed-top navbar-light bg-faded">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#CollapsingNavbar" aria-controls="CollapsingNavbar" aria-expanded="false" aria-label="Toggle navigation">
    &#9776;
  </button>
    <a id="navbar-brand" class="navbar-brand" href="/">EVI</a>
    <% if user_signed_in? %>
      <div class="nav navbar-nav pull-xs-right hidden-md-up">
        <div id="gravatar" class="nav-item"><%= gravatar_for current_user %></div>
      </div>
    <% end %>
    <div class="collapse navbar-toggleable-xs" id="CollapsingNavbar">
    <% if user_signed_in? %>
      <div class="nav navbar-nav">
        <div class="nav-item dropdown hidden-md-up">
          <a class="nav-link dropdown-toggle" id="navBarDropdown1" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create</a>
          <div class="dropdown-menu" aria-labelledby="navBarDropDown1">
            <%= link_to 'Appointment', new_appointment_path, class: "nav-link user-header-dropdown-link top-list-item", data: {toggle: "collapse", target: "#CollapsingNavbar"}, remote: true %>
            <%= link_to 'Patient', new_patient_path, class: "nav-link user-header-dropdown-link", data: {toggle: "collapse", target: "#CollapsingNavbar"}, remote: true%>
            <%= link_to 'Interpreter', new_user_registration_path, class: "nav-link user-header-dropdown-link", data: {toggle: "collapse", target: "#CollapsingNavbar"}, remote: true%>
            <%= link_to 'Invoice', new_invoice_path, class: "nav-link user-header-dropdown-link", data: {toggle: "collapse", target: "#CollapsingNavbar"}, remote: true%>
            <%= link_to 'Invoices', auto_create_path, class: "nav-link user-header-dropdown-link", data: {toggle: "collapse", target: "#CollapsingNavbar"}, remote: true%>
          </div>
        </div>
        <div class="nav-item dropdown hidden-md-up">
          <a class="nav-link dropdown-toggle" id="navbarDropdown2" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">List</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
            <%= link_to 'Appointments', all_appointments_path, class: "nav-link user-header-dropdown-link top-list-item", data: {toggle: "collapse", target: "#CollapsingNavbar"}, remote: true%>
            <%= link_to 'Patients', patients_path, class: "nav-link user-header-dropdown-link", data: {toggle: "collapse", target: "#CollapsingNavbar"}, remote: true%>
            <%= link_to 'Invoices', invoices_path, class: "nav-link user-header-dropdown-link", data: {toggle: "collapse", target: "#CollapsingNavbar"}, remote: true%>
            <% if current_user.admin %>
              <%= link_to 'Interpreters', users_path, class: "nav-link user-header-dropdown-link", data: {toggle: "dropdown", target: "#navBarDropdown2"}, remote: true%>
            <% end %>
          </div>
        </div>
        <div class="nav-item dropdown hidden-sm-down">
          <a class="nav-link dropdown-toggle" id="navBarDropdown1" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create</a>
          <div class="dropdown-menu" aria-labelledby="navBarDropDown1">
            <%= link_to 'Appointment', new_appointment_path, class: "nav-link user-header-dropdown-link top-list-item", data: {toggle: "dropdown", target: "#navBarDropDown1"}, remote: true %>
            <%= link_to 'Patient', new_patient_path, class: "nav-link user-header-dropdown-link", data: {toggle: "dropdown", target: "#navBarDropDown1"}, remote: true%>
            <%= link_to 'Interpreter', new_user_registration_path, class: "nav-link user-header-dropdown-link", data: {toggle: "dropdown", target: "#navBarDropDown1"}, remote: true%>
            <%= link_to 'Invoice', new_invoice_path, class: "nav-link user-header-dropdown-link", data: {toggle: "dropdown", target: "#navBarDropDown1"}, remote: true%>
            <%= link_to 'Invoices', auto_create_path, class: "nav-link user-header-dropdown-link", data: {toggle: "dropdown", target: "#navBarDropDown1"}, remote: true%>
          </div>
        </div>
        <div class="nav-item dropdown hidden-sm-down">
          <a class="nav-link dropdown-toggle" id="navbarDropdown2" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">List</a>
          <div class="dropdown-menu" aria-labelledby="navBarDropdown2">
            <%= link_to 'Appointments', all_appointments_path, class: "nav-link user-header-dropdown-link top-list-item", data: {toggle: "dropdown", target: "#navBarDropdown2"}, remote: true%>
            <%= link_to 'Patients', patients_path, class: "nav-link user-header-dropdown-link", data: {toggle: "dropdown", target: "#navBarDropdown2"}, remote: true%>
            <%= link_to 'Invoices', invoices_path, class: "nav-link user-header-dropdown-link", data: {toggle: "dropdown", target: "#navBarDropdown2"}, remote: true%>
            <% if current_user.admin %>
              <%= link_to 'Interpreters', users_path, class: "nav-link user-header-dropdown-link", data: {toggle: "dropdown", target: "#navBarDropdown2"}, remote: true%>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="pull-xs-right">
        <% if user_signed_in? %>
          <div id="welcome-header" class="nav-item hidden-md-down nav-link">Welcome back <%= current_user.first_name%>!</div>
          <div id="logout" class="nav-item"><%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "nav-link") %></div>
          <div id="gravatar" class="nav-item hidden-md-down"><%= gravatar_for current_user %></div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EVI</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="container-fluid">
      <div class="text-center notice-and-alert">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <div class="col-sm-12">
        <%= render "layouts/user_header" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>